# Site settings
title: Corra L. Morgan
email: corram10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Corra Morgan
email: corram10@gmail.com
facebook_username: corra.morgan.1
twitter_username:
github_username: corralynn
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: (814) 316-2696
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
